name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Prepare Test 1
      run: python3 find_lowest_number.py test_data/test1_input.txt lowest_number.txt
    - name: Test 1
      run: diff test_data/test1_expected.txt lowest_number.txt
    - name: Prepare Test 2
      run: python3 find_lowest_number.py test_data/test2_input.txt lowest_number.txt
    - name: Test 2
      run: diff test_data/test2_expected.txt lowest_number.txt
    - name: Prepare Test 3
      run: python3 find_lowest_number.py test_data/test3_input.txt lowest_number.txt
    - name: Test 3
      run: diff test_data/test3_expected.txt lowest_number.txt
