name: Automated Test
on: [push]
jobs:
  automated_test:
    name: Automated Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run python script
      run: python3 find_lowest_number.py test_data/test1_input.txt lowest_number.txt
    - name: Compare output to expected.
      run: diff lowest_number.txt test_data/test1_expected.txt
